### PR TITLE
Use NetworkManager to list access points

### PR DESCRIPTION
**Pull request by koterpillar**
`iwlist` isn't always available, try getting the access point list from NetworkManager. One of the advantages is that this method does not require `sudo`.

### CODE REVIEW

**Comment by kootenpv** [comment]
Hey, thanks a lot for your work!

I had a look at it, and I found a couple of issues. It might be best if you'd implement them as well, then I can pull them all in at once, working.

1. Please ensure that quality is an int()

2. We cannot allow `time nmcli -t -f state general status` to take 1.5 seconds. Sometimes access_points will only get called once, and like this it will double the time. Perhaps we can just check whether the network-manager has been installed (as it lacks on ubuntu)?

```

try: 
    d
    return True
except: 
    return False
```
Just checking for the executable is 0.006 seconds.

3. For which OS' do you think it works? I tested it, and it was working on my Arch Linux machine. It'd be interesting to know if it works on more.

What do you think?

I guess we can soon come to including your PR. Thanks once more!

**Comment by koterpillar** [comment]
Fixed 1 and 2 above. For the OS, I expect it to work in the default installations of Ubuntu, Fedora, as well as anything that uses GNOME desktop environment, as NetworkManager is a dependency of GNOME. I am running this on Arch Linux as well, but I did not have `iwlist` at all.

**Comment by kootenpv** [comment]
Thanks so much for following up! I'll let you know when it has been added in the new build!

**Comment by kootenpv** [comment]
Noting that:

```
def split_escaped(string, separator):
    """Split a string on separator, ignoring ones escaped by backslashes."""

    result = []
    current = ''
    escaped = False
    for char in string:
        if not escaped:
            if char == '\\':
                escaped = True
                continue
            elif char == separator:
                result.append(current)
                current = ''
                continue
        escaped = False
        current += char
    result.append(current)
    return result
```

It's a bit strange, is that "result.append" at the correct spot?

Also, pep8 complains about the possibility of not enough arguments to unpack:

`ssid, bssid, quality, security = split_escaped(line, ':')`

With error:

`[ERROR] Possible unbalanced tuple unpacking with sequence defined at line 22: left side has 4 label(s), r...`

Perhaps we can make that safer?

**Comment by koterpillar** [comment]
`result.append` must be in two places, the first is after each delimiter (`:`), the second is at the string end.

The unpacking is guaranteed to succeed by the arguments of `nmcli` - there are four fields requested.

I can switch the whole thing to the NetworkManager D-Bus API. This will make the whole thing safe from passing text around, but it will bring an additional dependency (https://pypi.python.org/pypi/python-networkmanager/).

**Comment by kootenpv** [comment]
Jumped a couple of versions, and added tests. You can see your changes in `access_points==0.2.28` and onwards.

**Comment by kootenpv** [comment]
I guess it is fine for now. Feel free to run the tests :) I think it's a stable version.

**Pull request merged**
